# example:
#   func:
#     - func/example.fc
#   tests:
#     - tests/example.fc

# task1:
#   func:
#     - func/1.fc
#   tests:
#     - tests/1.fc

task2:
  func:
    - func/2.fc
  tests:
    - tests/2.fc
