# example:
#   func:
#     - func/example.fc
#   tests:
#     - tests/example.fc

# task1:
#   func:
#     - func/1.fc
#   tests:
#     - tests/1.fc

# task2:
#   func:
#     - func/2.fc
#   tests:
#     - tests/2.fc

# task4:
#   func:
#     - func/typehelpers.fc
#     - func/4.fc
#   tests:
#     - tests/4.fc

task5:
  func:
    - func/typehelpers.fc
    - func/5.fc
  tests:
    - tests/5.fc